--Criação do Banco de Dados

CREATE DATABASE SENAI_SPMEDICALGROUP;

USE SENAI_SPMEDICALGROUP;

CREATE TABLE TIPO_USUARIOS(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(250) UNIQUE NOT NULL  
);

CREATE TABLE AREAS_CLINICAS(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(250) UNIQUE NOT NULL
);

CREATE TABLE CLINICAS(
	ID INT IDENTITY(1,1) PRIMARY KEY
	,NOME VARCHAR(250) NOT NULL
	,ENDERECO VARCHAR(250) NOT NULL
	,CNPJ CHAR(14) UNIQUE NOT NULL
	,CEP CHAR(8) NOT NULL
	,RAZAO_SOCIAL VARCHAR(250) NOT NULL
);

CREATE TABLE USUARIOS(
	ID INT IDENTITY(1,1) PRIMARY KEY
	,EMAIL VARCHAR(250) NOT NULL
	,SENHA VARCHAR(250) NOT NULL
	,ID_TIPO_USUARIO INT NOT NULL FOREIGN KEY REFERENCES TIPO_USUARIOS(ID)
	);


CREATE TABLE PRONTUARIOS(
	ID INT IDENTITY(1,1) PRIMARY KEY
	,ID_USUARIO INT NOT NULL FOREIGN KEY REFERENCES USUARIOS(ID)
	,RG CHAR(10) NOT NULL UNIQUE 
	,CPF CHAR(11) NOT NULL UNIQUE
	,TELEFONE CHAR(11)
	,ENDERECO VARCHAR(250) NOT NULL
	,DATA_NASCIMENTO DATE NOT NULL
);


CREATE TABLE MEDICOS(
	ID INT IDENTITY(1,1) PRIMARY KEY
	,NOME VARCHAR(250) NOT NULL
	,CRM VARCHAR(13) NOT NULL
	,ID_USUARIO INT NOT NULL FOREIGN KEY REFERENCES USUARIOS(ID)
	,ID_AREA_ATUACAO INT NOT NULL FOREIGN KEY REFERENCES AREAS_CLINICAS(ID)
	,ID_CLINICA INT NOT NULL FOREIGN KEY REFERENCES CLINICAS(ID)
);


CREATE TABLE CONSULTAS(
	ID INT IDENTITY(1,1) PRIMARY KEY
	,ID_PRONTUARIO INT NOT NULL FOREIGN KEY REFERENCES PRONTUARIOS(ID)
	,ID_MEDICO INT NOT NULL FOREIGN KEY REFERENCES MEDICOS(ID)
	,DATA_HORA DATETIME NOT NULL
	,DESCRICAO TEXT NOT NULL
	,STATUS VARCHAR(250) NOT NULL
);
